# Generated by Django 4.2.4 on 2023-09-01 19:19

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('server', 'Category')
    Category.objects.create(name='Groceries')
    Category.objects.create(name='Office supplies')
    Category.objects.create(name='Building materials')


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_category_id_alter_item_id'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_code=migrations.RunPython.noop),
    ]
